apiVersion: apps/v1

kind: Deployment

metadata:

  name: java-deployment

spec:

  selector:

    matchLabels:

      app: java

  replicas: 2 # tells deployment to run 2 pods matching the template

  template:

    metadata:

      labels:

        app: java

    spec:

      containers:

      - name: javaContainer

        image: abhishekchauhannagarro/dockerdemo:v2

        ports:

        - containerPort: 8080
